import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { collection, query, where, getDocs } from 'firebase/firestore';
import { db } from '../firebase';
import { appId } from '../constants';
import { format } from 'date-fns';

export const generatePDFReport = async (user, profile) => {
    if (!user) return;

    try {
        const doc = new jsPDF();

        // --- 1. Header & User Profile ---
        doc.setFontSize(22);
        doc.setTextColor(41, 128, 185); // Blue
        doc.text("Tripify User Report", 14, 20);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated on: ${format(new Date(), 'PPpp')}`, 14, 28);

        // User Details
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text(`Name: ${user.displayName || 'Traveler'}`, 14, 40);
        doc.text(`Email: ${user.email}`, 14, 46);
        doc.text(`Profile Score: ${profile?.metadata?.completenessScore ? Math.round(profile.metadata.completenessScore * 100) : 0}%`, 14, 52);

        // --- 2. Fetch Data ---
        // Fetch Trips owned by user or where user is collaborator
        // For simplicity in this report, we'll fetch trips where user is a collaborator
        const tripsQuery = query(
            collection(db, 'artifacts', appId, 'trips'),
            where('collaborators', 'array-contains', user.uid)
        );
        const tripsSnapshot = await getDocs(tripsQuery);
        const trips = tripsSnapshot.docs.map(d => ({ id: d.id, ...d.data() }));

        doc.setFontSize(16);
        doc.setTextColor(41, 128, 185);
        doc.text(`Trip Summary (${trips.length})`, 14, 65);

        // Trip Summary Table
        const tripTableData = trips.map(t => [
            t.tripName,
            format(new Date(t.createdAt), 'PP'),
            t.destination?.name || 'N/A',
            t.travelerCount,
            `$${t.totalCost || 0}` // Using default $ for summary or logic to detect currency could be added
        ]);

        autoTable(doc, {
            startY: 70,
            head: [['Trip Name', 'Created', 'Destination', 'Travelers', 'Total Cost']],
            body: tripTableData,
            theme: 'grid',
            headStyles: { fillColor: [41, 128, 185] },
        });

        // --- 3. Detailed Expenses per Trip ---
        let currentY = doc.lastAutoTable.finalY + 20;

        for (const trip of trips) {
            // Check if we need a page break
            if (currentY > 250) {
                doc.addPage();
                currentY = 20;
            }

            // Fetch Expenses for this trip
            const expQuery = query(collection(db, 'artifacts', appId, 'trips', trip.id, 'expenses'));
            const expSnapshot = await getDocs(expQuery);
            const expenses = expSnapshot.docs.map(d => d.data());

            if (expenses.length > 0) {
                doc.setFontSize(14);
                doc.setTextColor(0);
                doc.text(`Expenses: ${trip.tripName}`, 14, currentY);

                const expenseData = expenses.map(e => [
                    format(new Date(e.date), 'PP'),
                    e.description || e.category,
                    e.category,
                    e.paidBy === user.uid ? 'Me' : 'Others',
                    `${e.currency} ${e.amount}`
                ]);

                autoTable(doc, {
                    startY: currentY + 5,
                    head: [['Date', 'Description', 'Category', 'Paid By', 'Amount']],
                    body: expenseData,
                    theme: 'striped',
                    headStyles: { fillColor: [52, 73, 94] },
                    margin: { left: 14 }
                });

                currentY = doc.lastAutoTable.finalY + 15;
            }
        }

        // --- Footer ---
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text('Auto-generated by Tripify', 14, doc.internal.pageSize.height - 10);
            doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
        }

        // Save
        doc.save(`Tripify_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
        return true;

    } catch (error) {
        console.error("PDF Generation Error:", error);
        throw error;
    }
};
